### ISSUE TITLE
Posting to /:user/createMarkov yields 500 if user file does not exist

### ISSUE THREAD

**Issue by widarlein** [Unarmed/internet-on-a-stick#1]
When posting to /widar/createMarkov the service returns 500 Eternal Server Error and the following stacktrace is produced

<pre>java.io.FileNotFoundException: data\widar\circlejerk\markov.json (The system cannot find the path specified)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
    at se.carlengstrom.internetonastick.http.HttpServer.postCreateMarkov(HttpServer.java:74)
    at se.carlengstrom.internetonastick.http.HttpServer.lambda$new$2(HttpServer.java:38)
    at spark.RouteImpl$1.handle(RouteImpl.java:58)
    at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
    at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by Unarmed** [comment]
Thank you! Bad use of the FileOutputStream on my end. Will address it tonight.

**Comment by Unarmed** [comment]
Also, i really hope you did not get an _eternal_ server error, because then we are really out of luck

**Comment by Unarmed** [comment]
Fixed in d9f7267
