### ISSUE TITLE
Endpoint /:user/:markov returns 500 on empty markov

### ISSUE THREAD

**Issue by widarlein** [Unarmed/internet-on-a-stick#3]
If you create a markov and then perfom a get without appending data, an exception is thrown and 500 is returned

<pre>
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at se.carlengstrom.internetonastick.model.Markov.generateSentence(Markov.java:132)
    at se.carlengstrom.internetonastick.http.HttpServer.getMarkov(HttpServer.java:150)
    at se.carlengstrom.internetonastick.http.HttpServer.lambda$new$7(HttpServer.java:47)
    at spark.RouteImpl$1.handle(RouteImpl.java:58)
    at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
    at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by Unarmed** [comment]
I'm guessing that a HTTP 200 and an empty string as a payload would be prefferable?

**Comment by Unarmed** [comment]
Fixed in: 3d93d8258cf6776db6791bcacbf97756f587a4c4

I opted for not returning 200, because the server really cannot process the request. Instead you will now see a [400](https://http.cat/400) with the following message:

{"message":"Cannot generate sentences from empty markov chain"}
