### ISSUE TITLE
Appending lines to markov seems not to be very thread safe

### ISSUE THREAD

**Issue by widarlein** [Unarmed/internet-on-a-stick#4]
<pre>
Exception in thread "Thread-506" java.util.ConcurrentModificationException
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1545)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at se.carlengstrom.internetonastick.model.Markov.connectAncestorsOf(Markov.java:95)
    at se.carlengstrom.internetonastick.model.Markov.insertSentence(Markov.java:52)
    at se.carlengstrom.internetonastick.model.builders.MarkovBuilder.appendMarkovFromLineDelimitedText(MarkovBuilder.java:44)
    at se.carlengstrom.internetonastick.job.AppendLineFileToMarkovJob.run(AppendLineFileToMarkovJob.java:35)
    at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by Unarmed** [comment]
Your machine or mine? Are you by any chance running two inserts at the same time?

**Comment by widarlein** [comment]
My machine. I'm running the inserts sequentially  wrt calls to the appendLine endpoint. But I must confess that they are run very fast after one another, so I guess that the jobs that are spawned are running somewhat concurrently.

**Comment by widarlein** [comment]
Also, My machines! https://www.youtube.com/watch?v=p1F7hZzIckA

**Comment by Unarmed** [comment]
I think the jobs will run in parallel then. But your use case should be supported anyway, I just have to implement some basic queueing.

Also appendLine is a terrible name for the endpoint because it accepts as much text as you want, it just uses \n to separate that body of text into sentences (which is another poorly chosen word). 

So when i upload irc-logs I issue _one_ call with three years worth of logs and then I play the waiting game. Maybe that could be a feasable workaround until I get a patch out?

**Comment by Unarmed** [comment]
So as of c2ef46a28ffbc106dea0c47c28ad10ae631f67ef there is a very basic scheduler that makes sure that there is only one job running for each markov. That should stop any of the threading issues that two simultaneous jobs might create.

I think that the sentence generation is safe to use while jobs operate on the markov, or at least I haven't seen any evidence of the contrary, so I hope that threading issues are decreased from now on.

The scheduler is not perfect, so there is still a lot to do there, but I think it's sufficient for the type of errors we have now. The API for getting a particular job has been updated to reflect the scheduling.
